# -*- coding: utf-8 -*-
"""quicksort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_RQsCJpeRJr6FcZPEKiC1SbvRF4yhw-
"""

data = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]
def quicksort(arr):
  if len(arr)<=1:
    return arr
  pivot = arr[0]
  left = 0
  right = len(arr)-1
  while left!=right:
    while left!=right and arr[right]>=pivot:
      right -=1
    while left!=right and arr[left]<=pivot:
      left +=1
    arr[left], arr[right] = arr[right], arr[left]
  arr[0], arr[right] = arr[right], arr[0]
  print(arr)

  return quicksort(arr[:right])+[pivot]+quicksort(arr[right+1:])
quicksort(data)